variables:
  appscanApiKeyId: $APPSCAN_KEY
  appscanApiKeySecret: $APPSCAN_SECRET
  appscanAppName: $APP_NAME
  serviceUrl: 'cloud.appscan.com'
  assetGroupId: $APPSCAN_ASSET
  scanName: $CI_PROJECT_NAME-$CI_JOB_ID
  urlTarget: 'https://demo.testfire.net'
  loginDastConfig: 'login.dast.config'
  manualExplorerDastConfig: 'manualexplorer.dast.config'
  appscanPresenceId: ''
  sevSecGw: 'criticalIssues'
  maxIssuesAllowed: 100

include:
  - remote: 'https://raw.githubusercontent.com/HCL-TECH-SOFTWARE/appscan-gitlab-integration/V2/yaml/appscanasoc_scan_dast.yaml'

stages:
- scan-dast

scan-job:
  stage: scan-dast
