variables:
  appscanApiKeyId: $APPSCAN_KEY
  appscanApiKeySecret: $APPSCAN_SECRET
  appscanAppName: $APP_ID
  serviceUrl: 'cloud.appscan.com'
  assetGroupId: 'xxxxxxxxxxxxxx'
  scanName: $APP_ID-$CI_JOB_ID
  scanLatestCommitFiles: 'no' # yes or no. Scan only the latest committed files. Partial scan.
  scoScan: 'no' # yes or no. Source Code Only scan. This option will not scan binaries.
  sevSecGw: 'criticalIssues'
  maxIssuesAllowed: 100

include:
  - remote: 'https://github.com/HCL-TECH-SOFTWARE/appscan-gitlab-integration/V2/yaml/appscanasoc_scan_sast.yaml'

stages:
- scan-sast

scan-job:
  stage: scan-sast
