variables:
  appscanApiKeyId: $APPSCAN_KEY
  appscanApiKeySecret: $APPSCAN_SECRET
  appscanAppName: $APP_NAME
  serviceUrl: 'cloud.appscan.com'
  assetGroupId: $APPSCAN_ASSET
  scanName: $CI_PROJECT_NAME-$CI_JOB_ID
  considerPkgManager: 'yes' #to ignore pkg manager files change to 'no'
  sevSecGw: 'criticalIssues'
  maxIssuesAllowed: 100

include:
  - remote: 'https://raw.githubusercontent.com/HCL-TECH-SOFTWARE/appscan-gitlab-integration/V2/yaml/appscan_scan_sca.yaml'

stages:
- scan-sca

scan-job:
  stage: scan-sca
