variables:
  appscanApiKeyId: $APPSCAN_KEY
  appscanApiKeySecret: $APPSCAN_SECRET
  appscanAppName: $APP_NAME
  assetGroupId: $APPSCAN_ASSET

stages:
- scan-sca

scan-sca:
  stage: scan-sca
  tags:
    - appscan
  script:

  - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscan_create_application_asoc.ps1 -OutFile appscan_create_application_asoc.ps1
  - .\appscan_create_application_asoc.ps1

  - Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/Integration-AppScan-onprem-and-Gitlab/main/scripts/appscan_scan_sca.ps1 -OutFile appscan_scan_sca.ps1
  - .\appscan_scan_sca.ps1

  artifacts:
    when: always
    paths:
      - "*.pdf"
